version: '3.7'
services:
  admin:
    build: .
    container_name: react
    command: npm start 
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    tty: true
